# .github/workflows/format-check.yml

# Name des Workflows, der in der GitHub Actions UI angezeigt wird
name: "Format Check"

# Trigger: Wann soll dieser Workflow ausgeführt werden?
on:
  # Bei jedem Push auf den main-Branch
  push:
    branches: [ "main" ]
  # Bei jedem Pull Request, der auf den main-Branch zielt
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

# Definition der auszuführenden Jobs
jobs:
  # Ein Job mit dem Namen "spotless"
  spotless:
    # Betriebssystem, auf dem der Job laufen soll
    runs-on: ubuntu-latest

    # Die einzelnen Schritte des Jobs
    steps:
      # Schritt 1: Code aus dem Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # Schritt 2: Java Development Kit (JDK) einrichten, da Gradle es benötigt
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Schritt 3: Gradle Wrapper ausführbar machen (gute Praxis)
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Schritt 4: Spotless Check ausführen
      # `./gradlew spotlessCheck` prüft die Formatierung, ohne Dateien zu ändern.
      # Der Befehl schlägt fehl (exit code != 0), wenn der Code nicht korrekt
      # formatiert ist, was den gesamten Workflow fehlschlagen lässt.
      - name: Run Spotless Check
        run: ./gradlew spotlessCheck
        
